from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_BUILD = r"build\rtx3060-runtime\windows-vs2022-cuda86-release\Release"
DEFAULT_REPO_SAFE = "HauhauCS__Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive"
DEFAULT_TARGET = "Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf"


def storage_root(value: str | None) -> Path:
    return Path(value or os.environ.get("RTXLLM_STORAGE_ROOT", r"E:\AI project"))


def default_build_dir(root: Path) -> Path:
    return root / DEFAULT_BUILD


def default_target_model(root: Path) -> Path:
    return root / "models" / DEFAULT_REPO_SAFE / DEFAULT_TARGET


def default_target_q4_payload(root: Path) -> Path:
    return root / "tmp" / "blk0_attn_qkv_q4_payload.bin"


def default_target_q4_blocks(root: Path) -> Path:
    return root / "tmp" / "blk0_attn_qkv_q4_blocks.bin"


def latest_q4k_pack_manifest(root: Path) -> Path | None:
    pack_root = root / "packs" / "q4k" / DEFAULT_TARGET.removesuffix(".gguf")
    if not pack_root.exists():
        return None
    candidates = [
        path / "manifest.json"
        for path in pack_root.iterdir()
        if path.is_dir() and path.name.isdigit() and (path / "manifest.json").exists()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda path: int(path.parent.name))


def latest_iq2s_pack_manifest(root: Path) -> Path | None:
    pack_root = root / "packs" / "iq" / DEFAULT_TARGET.removesuffix(".gguf") / "iq2_s"
    if not pack_root.exists():
        return None
    candidates = [
        path / "manifest.json"
        for path in pack_root.iterdir()
        if path.is_dir() and path.name.isdigit() and (path / "manifest.json").exists()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda path: int(path.parent.name))


def latest_iq3s_pack_manifest(root: Path) -> Path | None:
    pack_root = root / "packs" / "iq" / DEFAULT_TARGET.removesuffix(".gguf") / "iq3_s"
    if not pack_root.exists():
        return None
    candidates = [
        path / "manifest.json"
        for path in pack_root.iterdir()
        if path.is_dir() and path.name.isdigit() and (path / "manifest.json").exists()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda path: int(path.parent.name))


def latest_iq_layer_pack_manifest(root: Path, type_label: str, layer: int) -> Path | None:
    pack_root = (
        root
        / "packs"
        / "iq"
        / DEFAULT_TARGET.removesuffix(".gguf")
        / f"{type_label}_layer{layer}"
    )
    if not pack_root.exists():
        return None
    candidates = [
        path / "manifest.json"
        for path in pack_root.iterdir()
        if path.is_dir() and path.name.isdigit() and (path / "manifest.json").exists()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda path: int(path.parent.name))


def latest_q5k_pack_manifest(root: Path) -> Path | None:
    pack_root = root / "packs" / "q5k" / DEFAULT_TARGET.removesuffix(".gguf")
    if not pack_root.exists():
        return None
    candidates = [
        path / "manifest.json"
        for path in pack_root.iterdir()
        if path.is_dir() and path.name.isdigit() and (path / "manifest.json").exists()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda path: int(path.parent.name))


def q4k_validation_manifest(root: Path) -> Path | None:
    path = (
        root
        / "packs"
        / "q4k"
        / DEFAULT_TARGET.removesuffix(".gguf")
        / "validation_reps"
        / "manifest.json"
    )
    return path if path.exists() else None


def sanitize_label(value: str) -> str:
    label = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return label.strip("._-") or "native"


def extract_json_object(output: str) -> dict[str, object]:
    start = output.find("{")
    stop = output.rfind("}")
    if start < 0 or stop < start:
        raise ValueError("no JSON object found in command output")
    parsed = json.loads(output[start : stop + 1])
    if not isinstance(parsed, dict):
        raise ValueError("native benchmark output was not a JSON object")
    return parsed


def run_command(command: list[str], timeout: int) -> dict[str, object]:
    start = time.perf_counter()
    proc = subprocess.run(
        command,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
    )
    wall_ms = (time.perf_counter() - start) * 1000.0
    result = {
        "command": command,
        "returncode": proc.returncode,
        "process_wall_ms": wall_ms,
        "output_tail": proc.stdout[-6000:],
    }
    try:
        result["metrics"] = extract_json_object(proc.stdout)
    except (json.JSONDecodeError, ValueError) as exc:
        result["parse_error"] = str(exc)
    return result


def write_metric_artifact(
    bench_dir: Path,
    run: dict[str, object],
    *,
    stamp: int,
    generated_at: str,
) -> Path | None:
    metrics = run.get("metrics")
    if not isinstance(metrics, dict):
        return None
    path_name = str(metrics.get("path", "native_benchmark"))
    run_name = sanitize_label(str(run.get("name", path_name)))
    out_path = bench_dir / f"{path_name}_{run_name}_{stamp}.json"
    artifact = {
        **metrics,
        "generated_at": generated_at,
        "command": run["command"],
        "returncode": run["returncode"],
        "process_wall_ms": run["process_wall_ms"],
        "output_tail": run["output_tail"],
    }
    out_path.write_text(json.dumps(artifact, indent=2), encoding="utf-8")
    return out_path


def write_markdown(path: Path, result: dict[str, object]) -> None:
    lines = [
        "# Native Benchmark Harness",
        "",
        f"Generated: `{result['generated_at']}`",
        f"Build dir: `{result['build_dir']}`",
        "",
        "| exe | args | status | return code | check | valid tensors | invalid tensors | q4k smoke | q4k dequant | q4k checksum | q4k absmax | weight source | weight checksum | steps | steps/s | p50 ms | p95 ms | p99 ms | graph replay | artifact |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for run in result["runs"]:
        metrics = run.get("metrics") if isinstance(run, dict) else None
        if not isinstance(metrics, dict):
            metrics = {}
        q4k_smoke = metrics.get("q4k_smoke")
        if not isinstance(q4k_smoke, dict):
            q4k_smoke = {}
        lines.append(
            "| "
            + " | ".join(
                [
                    str(run.get("name", "")),
                    "`" + " ".join(str(arg) for arg in run.get("args", [])) + "`",
                    str(run.get("status", "")),
                    str(run.get("returncode", "")),
                    str(metrics.get("reference_passed", "")),
                    str(metrics.get("valid_tensors", "")),
                    str(metrics.get("invalid_tensors", "")),
                    str(q4k_smoke.get("valid", "")),
                    str(q4k_smoke.get("dequant_valid", "")),
                    str(q4k_smoke.get("packed_q4_checksum", "")),
                    fmt(q4k_smoke.get("dequant_absmax")),
                    str(metrics.get("weight_source", "")),
                    str(metrics.get("host_weight_checksum", "")),
                    str(metrics.get("steps", "")),
                    fmt(metrics.get("steps_per_second")),
                    fmt(metrics.get("p50_ms")),
                    fmt(metrics.get("p95_ms")),
                    fmt(metrics.get("p99_ms")),
                    fmt(metrics.get("graph_replay_rate")),
                    str(run.get("artifact", "")),
                ]
            )
            + " |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fmt(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run native C++/CUDA benchmark executables.")
    parser.add_argument("--storage-root", default=None)
    parser.add_argument("--build-dir", default=None)
    parser.add_argument("--timeout", type=int, default=120)
    args = parser.parse_args()

    root = storage_root(args.storage_root)
    bench_dir = root / "benchmarks"
    bench_dir.mkdir(parents=True, exist_ok=True)
    build_dir = Path(args.build_dir) if args.build_dir else default_build_dir(root)
    generated_at = datetime.now(timezone.utc).isoformat()
    stamp = int(time.time())
    target_model = default_target_model(root)
    target_q4_payload = default_target_q4_payload(root)
    target_q4_blocks = default_target_q4_blocks(root)
    q4k_pack_manifest = latest_q4k_pack_manifest(root)
    q4k_pack_validation_manifest = q4k_validation_manifest(root)
    iq2s_pack_manifest = latest_iq2s_pack_manifest(root)
    iq3s_pack_manifest = latest_iq3s_pack_manifest(root)
    iq2s_layer1_pack_manifest = latest_iq_layer_pack_manifest(root, "iq2_s", 1)
    iq3s_layer1_pack_manifest = latest_iq_layer_pack_manifest(root, "iq3_s", 1)
    q5k_pack_manifest = latest_q5k_pack_manifest(root)

    runs = []
    specs = [
        {
            "name": "runtime_layer_plan_selftest",
            "exe": "runtime_layer_plan_selftest.exe",
            "args": [],
        },
        {"name": "runtime_bench", "exe": "runtime_bench.exe", "args": []},
        {"name": "runtime_graph_bench", "exe": "runtime_graph_bench.exe", "args": []},
        {
            "name": "runtime_fused_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "reference_64x128",
                "--rows",
                "64",
                "--cols",
                "128",
                "--steps",
                "4",
                "--kv-mib",
                "1",
                "--page-words",
                "256",
                "--active-pages",
                "16",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_bench_default",
            "exe": "runtime_fused_bench.exe",
            "args": ["--label", "default"],
        },
        {
            "name": "runtime_gguf_probe_iq2m",
            "exe": "runtime_gguf_probe.exe",
            "args": [
                "--model",
                str(target_model),
                "--q4k-tensor",
                "blk.0.attn_qkv.weight",
                "--dump-q4k-payload",
                str(target_q4_payload),
                "--dump-q4k-blocks",
                str(target_q4_blocks),
            ],
        },
        {
            "name": "runtime_fused_bench_stress",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "stress_8192x8192",
                "--steps",
                "128",
                "--rows",
                "8192",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_shared_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_shared_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "shared",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_warp_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_warp_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "warp",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_broadcast_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_broadcast_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "broadcast",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_vec4_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_vec4x2_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4x2_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4x2",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_vec4x4_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4x4_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4x4",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_blocks_predecoded_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_predecoded_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "predecoded",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_split_predecoded_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_predecoded_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-predecoded",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_split_half_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_half_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-half",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_split_compact_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_compact_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-compact",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_q4k_split_native_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_native_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-native",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_packed_vec4x4_reference_check",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_payload_vec4x4_reference",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--steps",
                "1",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--weights-file",
                str(target_q4_payload),
                "--packed-kernel",
                "vec4x4",
                "--check-only",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--weights-file",
                str(target_q4_payload),
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_payload_vec4x4_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_payload_vec4x4_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--weights-file",
                str(target_q4_payload),
                "--packed-kernel",
                "vec4x4",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_shared_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_shared_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "shared",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_warp_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_warp_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "warp",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_broadcast_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_broadcast_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "broadcast",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_vec4_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_vec4x2_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4x2_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4x2",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_vec4x4_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_vec4x4_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "vec4x4",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_blocks_predecoded_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_blocks_predecoded_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-kernel",
                "predecoded",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_split_predecoded_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_predecoded_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-predecoded",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_split_half_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_half_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-half",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_split_compact_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_compact_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-compact",
            ],
        },
        {
            "name": "runtime_fused_bench_target_q4k_split_native_blk0",
            "exe": "runtime_fused_bench.exe",
            "args": [
                "--label",
                "target_q4k_split_native_blk0",
                "--steps",
                "128",
                "--rows",
                "2048",
                "--cols",
                "8192",
                "--kv-mib",
                "64",
                "--active-pages",
                "512",
                "--q4k-blocks-file",
                str(target_q4_blocks),
                "--q4k-payload-file",
                str(target_q4_payload),
                "--q4k-kernel",
                "split-native",
            ],
        },
    ]
    if q4k_pack_validation_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_fused_q4k_manifest_blk0_reference_check",
                    "exe": "runtime_fused_bench.exe",
                    "args": [
                        "--label",
                        "manifest_validation_blk0",
                        "--steps",
                        "1",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                        "--q4k-manifest",
                        str(q4k_pack_validation_manifest),
                        "--q4k-tensor",
                        "blk.0.attn_qkv.weight",
                        "--check-only",
                    ],
                },
                {
                    "name": "runtime_fused_q4k_manifest_blk3_reference_check",
                    "exe": "runtime_fused_bench.exe",
                    "args": [
                        "--label",
                        "manifest_validation_blk3",
                        "--steps",
                        "1",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                        "--q4k-manifest",
                        str(q4k_pack_validation_manifest),
                        "--q4k-tensor",
                        "blk.3.attn_v.weight",
                        "--check-only",
                    ],
                },
            ]
        )
    if q4k_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_fused_bench_q4k_manifest_blk0",
                    "exe": "runtime_fused_bench.exe",
                    "args": [
                        "--label",
                        "manifest_full_blk0",
                        "--steps",
                        "16",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--q4k-tensor",
                        "blk.0.attn_qkv.weight",
                    ],
                },
                {
                    "name": "runtime_fused_bench_q4k_manifest_blk3",
                    "exe": "runtime_fused_bench.exe",
                    "args": [
                        "--label",
                        "manifest_full_blk3",
                        "--steps",
                        "16",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--q4k-tensor",
                        "blk.3.attn_v.weight",
                    ],
                },
                {
                    "name": "runtime_q4k_sequence_bench_full40_chained",
                    "exe": "runtime_q4k_sequence_bench.exe",
                    "args": [
                        "--label",
                        "q4k_sequence_full40_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--limit",
                        "40",
                        "--steps",
                        "16",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                    ],
                },
                {
                    "name": "runtime_q4k_sequence_bench_full40_nochain",
                    "exe": "runtime_q4k_sequence_bench.exe",
                    "args": [
                        "--label",
                        "q4k_sequence_full40_nochain",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--limit",
                        "40",
                        "--steps",
                        "16",
                        "--kv-mib",
                        "64",
                        "--active-pages",
                        "512",
                        "--no-chain-activation",
                    ],
                },
            ]
        )
    if iq2s_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_iq2s_probe_attn_gate",
                    "exe": "runtime_iq_probe.exe",
                    "args": [
                        "--label",
                        "iq2s_probe_attn_gate",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--tensor",
                        "blk.0.attn_gate.weight",
                        "--steps",
                        "16",
                    ],
                },
                {
                    "name": "runtime_iq2s_probe_ffn_gate_exps",
                    "exe": "runtime_iq_probe.exe",
                    "args": [
                        "--label",
                        "iq2s_probe_ffn_gate_exps",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_gate_exps.weight",
                        "--steps",
                        "8",
                    ],
                },
                {
                    "name": "runtime_iq2s_decode_attn_gate",
                    "exe": "runtime_iq_matvec_probe.exe",
                    "args": [
                        "--label",
                        "iq2s_decode_attn_gate",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--tensor",
                        "blk.0.attn_gate.weight",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_iq2s_decode_ffn_gate_exps",
                    "exe": "runtime_iq_matvec_probe.exe",
                    "args": [
                        "--label",
                        "iq2s_decode_ffn_gate_exps",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_gate_exps.weight",
                        "--rows-limit",
                        "8",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "8",
                    ],
                },
                {
                    "name": "runtime_iq2s_sequence_limit2_chained",
                    "exe": "runtime_iq_sequence_bench.exe",
                    "args": [
                        "--label",
                        "iq2s_sequence_limit2_chained",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--limit",
                        "2",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_iq2s_sequence_limit2_nochain",
                    "exe": "runtime_iq_sequence_bench.exe",
                    "args": [
                        "--label",
                        "iq2s_sequence_limit2_nochain",
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--limit",
                        "2",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--no-chain-activation",
                    ],
                },
            ]
        )
    if iq3s_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_iq3s_probe_ffn_down_exps",
                    "exe": "runtime_iq_probe.exe",
                    "args": [
                        "--label",
                        "iq3s_probe_ffn_down_exps",
                        "--iq-manifest",
                        str(iq3s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_down_exps.weight",
                        "--steps",
                        "8",
                    ],
                },
                {
                    "name": "runtime_iq3s_probe_ffn_down_shexp",
                    "exe": "runtime_iq_probe.exe",
                    "args": [
                        "--label",
                        "iq3s_probe_ffn_down_shexp",
                        "--iq-manifest",
                        str(iq3s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_down_shexp.weight",
                        "--steps",
                        "8",
                    ],
                },
                {
                    "name": "runtime_iq3s_decode_ffn_down_exps",
                    "exe": "runtime_iq_matvec_probe.exe",
                    "args": [
                        "--label",
                        "iq3s_decode_ffn_down_exps",
                        "--iq-manifest",
                        str(iq3s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_down_exps.weight",
                        "--rows-limit",
                        "8",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "8",
                    ],
                },
                {
                    "name": "runtime_iq3s_decode_ffn_down_shexp",
                    "exe": "runtime_iq_matvec_probe.exe",
                    "args": [
                        "--label",
                        "iq3s_decode_ffn_down_shexp",
                        "--iq-manifest",
                        str(iq3s_pack_manifest),
                        "--tensor",
                        "blk.0.ffn_down_shexp.weight",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "1",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
            ]
        )
    if q4k_pack_manifest and iq2s_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_mixed_layer0_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_mixed_layer0_nochain",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_nochain",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--no-chain-activation",
                    ],
                },
            ]
        )
    if q4k_pack_manifest and iq2s_pack_manifest and q5k_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_mixed_layer0_output_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_output_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_mixed_layer0_output_nochain",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_output_nochain",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--no-chain-activation",
                    ],
                },
            ]
        )
    if q4k_pack_manifest and iq2s_pack_manifest and iq3s_pack_manifest and q5k_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_mixed_layer0_iq3_output_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_iq3_output_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_mixed_layer0_iq3_output_reference_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_iq3_output_reference_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                    ],
                },
                {
                    "name": "runtime_mixed_layer0_iq3_output_reference_roleplan",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_iq3_output_reference_roleplan",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                    ],
                },
                {
                    "name": "runtime_mixed_layer0_iq3_output_nochain",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer0_iq3_output_nochain",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "0",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--no-chain-activation",
                    ],
                },
            ]
        )
    if (
        q4k_pack_manifest
        and iq2s_layer1_pack_manifest
        and iq3s_layer1_pack_manifest
        and q5k_pack_manifest
    ):
        specs.extend(
            [
                {
                    "name": "runtime_mixed_layer1_iq3_output_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_chained",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_chained",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_scratch",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_scratch",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--phase-scratch",
                        "attention_qkv_scratch:attention:8192",
                        "--phase-scratch",
                        "ssm_state_scratch:ssm:4096",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_graphbucket",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_graphbucket",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--graph-bucket-count",
                        "3",
                        "--graph-query-bucket",
                        "1",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionphase",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionphase",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-scratch",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionreduce",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionreduce",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-reduce",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionwindow",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionwindow",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheadwindow",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheadwindow",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheaddim",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheaddim",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-dim-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheadtile",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheadtile",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-tile-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheadgroup",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheadgroup",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-group-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheadfused",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheadfused",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-group-fused",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_attentionheadrope",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_attentionheadrope",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--attention-phase-mode",
                        "qkv-head-group-rope-window",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ssmphase",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ssmphase",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ssm-phase-mode",
                        "recurrent-state",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ssmscan",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ssmscan",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ssm-phase-mode",
                        "scan-scratch",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ssmselective",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ssmselective",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ssm-phase-mode",
                        "selective-scan",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ssmsource",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ssmsource",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ssm-phase-mode",
                        "source-parameterized",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ssmsourcefused",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ssmsourcefused",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ssm-phase-mode",
                        "source-parameterized-fused",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_outputphase",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_outputphase",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_phaseaware",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_phaseaware",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--feedback-mode",
                        "phase-aware-ffn-silu",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_gated",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_gated",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--feedback-mode",
                        "phase-aware-ffn-gated-silu",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_ffnphase",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_ffnphase",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_allphase",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_allphase",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                        "--attention-phase-mode",
                        "qkv-head-group-window",
                        "--ssm-phase-mode",
                        "scan-scratch",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_allphase_rope",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_allphase_rope",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                        "--attention-phase-mode",
                        "qkv-head-group-rope-window",
                        "--ssm-phase-mode",
                        "scan-scratch",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_allphase_selective",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_allphase_selective",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                        "--attention-phase-mode",
                        "qkv-head-group-window",
                        "--ssm-phase-mode",
                        "selective-scan",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_allphase_source",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_allphase_source",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                        "--attention-phase-mode",
                        "qkv-head-group-window",
                        "--ssm-phase-mode",
                        "source-parameterized",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
                {
                    "name": "runtime_mixed_layer1_iq3_output_reference_roleplan_allphase_sourcefused",
                    "exe": "runtime_mixed_sequence_bench.exe",
                    "args": [
                        "--label",
                        "mixed_layer1_iq3_output_reference_roleplan_allphase_sourcefused",
                        "--q4k-manifest",
                        str(q4k_pack_manifest),
                        "--iq-manifest",
                        str(iq2s_layer1_pack_manifest),
                        "--extra-iq-manifest",
                        str(iq3s_layer1_pack_manifest),
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--q5k-tensor",
                        "output.weight",
                        "--layer",
                        "1",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "4",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                        "--check-reference",
                        "--stage-order",
                        "role-plan",
                        "--strict-layer-plan",
                        "--ffn-phase-mode",
                        "gated-silu",
                        "--attention-phase-mode",
                        "qkv-head-group-window",
                        "--ssm-phase-mode",
                        "source-parameterized-fused",
                        "--output-phase-mode",
                        "final-token",
                    ],
                },
            ]
        )
    if q5k_pack_manifest:
        specs.extend(
            [
                {
                    "name": "runtime_q5k_probe_output",
                    "exe": "runtime_q5k_probe.exe",
                    "args": [
                        "--label",
                        "q5k_probe_output",
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--tensor",
                        "output.weight",
                        "--steps",
                        "8",
                    ],
                },
                {
                    "name": "runtime_q5k_decode_output",
                    "exe": "runtime_q5k_matvec_probe.exe",
                    "args": [
                        "--label",
                        "q5k_decode_output",
                        "--q5k-manifest",
                        str(q5k_pack_manifest),
                        "--tensor",
                        "output.weight",
                        "--rows-limit",
                        "64",
                        "--steps",
                        "8",
                        "--kv-mib",
                        "8",
                        "--page-words",
                        "256",
                        "--active-pages",
                        "64",
                    ],
                },
            ]
        )
    for spec in specs:
        name = str(spec["name"])
        exe = build_dir / str(spec["exe"])
        run: dict[str, object] = {
            "name": name,
            "exe": str(exe),
            "args": spec["args"],
            "status": "missing",
        }
        if exe.exists():
            run.update(run_command([str(exe), *spec["args"]], timeout=args.timeout))
            run["status"] = "ok" if run["returncode"] == 0 and "metrics" in run else "failed"
            artifact = write_metric_artifact(
                bench_dir, run, stamp=stamp, generated_at=generated_at
            )
            if artifact:
                run["artifact"] = str(artifact)
        runs.append(run)

    result = {
        "path": "native_harness",
        "generated_at": generated_at,
        "storage_root": str(root),
        "build_dir": str(build_dir),
        "runs": runs,
    }
    out_json = bench_dir / f"native_harness_{stamp}.json"
    out_md = bench_dir / f"native_harness_{stamp}.md"
    out_json.write_text(json.dumps(result, indent=2), encoding="utf-8")
    write_markdown(out_md, result)

    print(f"json={out_json}")
    print(f"markdown={out_md}")
    for run in runs:
        if "artifact" in run:
            print(f"artifact={run['artifact']}")
    return 0 if all(run["status"] == "ok" for run in runs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
